### ISSUE TITLE
Relationship to `gh` cli tool?

### ISSUE THREAD

**Issue by andreasabel** [tfausak/github-release#24]
@tfausak (I saw your publication on hackage.)
Nowadays there is the `gh release` command.  (I guess in 2016 when you created `github-release` there wasn't anything like that.)
How does your tool relate to this?
Can `gh` do everything now that `github-release` set out to do?

Maybe add a comparison to the README.

**Comment by tfausak** [comment]
No relation. 

The documentation already points to the [original Go version](https://github.com/github-release/github-release) of `github-release`, which was the inspiration for this project. 

The [`gh` CLI tool](https://cli.github.com) is relatively new. I don't know when exactly it was released or added support for releases. Before it, the [`hub` CLI tool](https://hub.github.com) did many of the same things. 

This project's goal is to provide a Haskell-based tool for people using Haskell toolchains. Although these days that's less important since various things on the marketplace can be used in GitHub Actions to do the same thing. That's even what this project does today!

https://github.com/tfausak/github-release/blob/f50b19b83efb2eacc3ece68307ca4bf1979f0519/.github/workflows/workflow.yaml#L173-L177
